<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.Azure.AIFoundry" Version="13.1.3-preview.1.26166.8" />
    <PackageVersion Include="Aspire.Hosting.Foundry" Version="13.2.2-preview.1.26207.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.4.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.4.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.23.0.137933" />
  </ItemGroup>
</Project>