<Project Sdk="Aspire.AppHost.Sdk/13.2.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>6b6e4620-425b-4a61-849f-ec028d99572b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!--
      Tip: Use AspireProjectMetadataTypeName with new projects and use the short name in AppHost.cs:
        builder.AddProject<SampleApi>(ResourceNames.SampleApi)
    -->
    <!--<ProjectReference Include="..\AI.Foundry.Local.RAG.SampleApi\AI.Foundry.Local.RAG.SampleApi.csproj" AspireProjectMetadataTypeName="SampleApi" />-->
    <ProjectReference Include="..\..\AI.Foundry.Local.RAG.Web\AI.Foundry.Local.RAG.Web.csproj" />
    <ProjectReference Include="..\AI.Foundry.Local.RAG.Shared\AI.Foundry.Local.RAG.Shared.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
