<Project Sdk="Aspire.AppHost.Sdk/13.2.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>6b6e4620-425b-4a61-849f-ec028d99572b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.Foundry.Local.RAG.Frontend\AI.Foundry.Local.RAG.Frontend\AI.Foundry.Local.RAG.Frontend.csproj" AspireProjectMetadataTypeName="Frontend" />
    <ProjectReference Include="..\AI.Foundry.Local.RAG.Shared\AI.Foundry.Local.RAG.Shared.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
